language: android
android:
        components:
                - platform-tools
                - build-tools-21.0.1
                - android-21
                - extra-android-m2repository
script:
        - ./gradlew build
before_install:
        - chmod +x Wilenco_App/gradlew
branches:
        only:
                - master
